# Generated by Django 3.2.17 on 2023-02-14 15:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="tags",
            field=models.JSONField(default=""),
            preserve_default=False,
        ),
    ]
